### ISSUE TITLE
Reproducing error

### ISSUE THREAD

**Issue by ntubertchen** [jnhwkim/ban-vqa#11]
Upon reproducing this result, I encounter the following error.
Traceback (most recent call last):
  File "main.py", line 96, in <module>
    train(model, train_loader, eval_loader, args.epochs, args.output, optim, epoch)
  File "/home/tingting/Documents/tingting/ban-vqa/train.py", line 72, in train
    pred, att = model(v, b, q, a)
  File "/home/tingting/tingting/lib/python3.5/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/tingting/tingting/lib/python3.5/site-packages/torch/nn/parallel/data_parallel.py", line 113, in forward
    replicas = self.replicate(self.module, self.device_ids[:len(inputs)])
  File "/home/tingting/tingting/lib/python3.5/site-packages/torch/nn/parallel/data_parallel.py", line 118, in replicate
    return replicate(module, device_ids)
  File "/home/tingting/tingting/lib/python3.5/site-packages/torch/nn/parallel/replicate.py", line 12, in replicate
    param_copies = Broadcast.apply(devices, *params)
RuntimeError: slice() cannot be applied to a 0-dim tensor

After tracing this code, I found that if I delete "nn.DataParallel(model).cuda()", it worked well.

I use 4 GTX 1080 ti. Have you encountered the same thing before?

**Comment by jnhwkim** [comment]
related to #7
