### ISSUE TITLE
error from tools/process.sh

### ISSUE THREAD

**Issue by sizhangyu** [jnhwkim/ban-vqa#26]
I have downloaded everything listed in tools/download.sh.
Could you provide the missing data as well?
Thank you.

>Traceback (most recent call last):
  File "tools/adaptive_detection_features_converter.py", line 199, in <module>
    extract('train', infiles, args.task)
  File "tools/adaptive_detection_features_converter.py", line 94, in extract
    imgids = utils.load_imageid(path_imgs[split])
  File "/home/sizhangyu/Documents/pytorch_code/ban-vqa/utils.py", line 47, in load_imageid
    images = load_folder(folder, 'jpg')
  File "/home/sizhangyu/Documents/pytorch_code/ban-vqa/utils.py", line 40, in load_folder
    for f in sorted(os.listdir(folder)):
FileNotFoundError: [Errno 2] No such file or directory: 'data/train2014'

**Comment by jnhwkim** [comment]
Would you refer to https://github.com/jnhwkim/ban-vqa/blob/master/tools/download_data.sh ?
